name: RpgAPI
main: com.vartala.soulofw0lf.rpgapi.RpgAPI
version: 0.2
author: Soulofw0lf
description: rpg Api designed by soulofw0lf and Linksy
depend: [RemoteEntities]

commands:
  RpgHelp:
    description: Rpg suite - Use /RpgHelp to view rpg commands and Descriptions!
  trade:
    description: /trade <accept/deny/player>
  money:
    description: /money - View your money